################################################################
#                                                              #
#    SklepMc Plugin                                            #
#                                                              #
#    Nie wiesz jak skonfigurować? Zerknij do dokumentacji!     #
#    https://manager.okaeri.eu/sklepmc/docs                    #
#                                                              #
################################################################


# Id sklepu.
shop: ""

# Klucz prywatny API.
key: ""

# Id serwera.
server-id: 0
